spring:
  application:
    name: chinaoracle-back

  # 默认 dev 环境
  profiles:
    include: datasource,mybatis-plus,redis,mail,cos
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # 开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 热部署
  devtools:
    restart:
      enabled: true
# 服务器相关  626359-9376 => namely-zero
server:
  address: 0.0.0.0
  port: 9376
  servlet:
    # 可全局设置上下文路径
    context-path:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
